### ISSUE TITLE
Scrolling on mac

### ISSUE THREAD

**Issue by erangell** [beakerbrowser/dat-wysiwywiki-app#3]
I forked Paul's wiki and edited my copy.  dat://testwiki-erangell.hashbase.io/
I cannot scroll down to see additional content.  I am running Beaker Browser v0.8.0-prerelease.2 on a mac with Sierra.  Scrolling also doesn't work on Microsoft Edge (I just tested the https link to my wiki).

Also is there any expectation of synchronization between the local copy of the wiki and the hosted copy on hashbase.io?  See attachment.
<img width="895" alt="screen shot 2018-03-16 at 6 23 13 am" src="https://user-images.githubusercontent.com/5579123/37516153-99b641f0-28e3-11e8-8b3b-ae4d9f390f8f.png">

**Comment by pfrazee** [comment]
Thanks I saw that too, will fix.

**Comment by pfrazee** [comment]
Finally fixed!
